config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/forms/github-search')

  scope(:forms) do
    resources :event_forms, path: 'github-search'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_form.rb
class EventForm < Form

  # @!attribute [string] user_name
  attr_accessor :user_name

  #Raise error if the user input for the GitHub username does not follow the user community rules.
  def validate_name!(name)
    raise Error::NameInvalidError if is_name_invalid?(name)
  end

  #Check to see if the user name is valid according to the GitHub join rules
  def is_name_invalid?(name)
    name.length > 39 or name.include? "--" or name[0] == "-" or name[name.length-1] == '-'
  end

  #Remove weird characters that would not belong in a name
  def sanitize_name!(name)
    name.gsub(/[^0-9A-z.\-]/, '')
  end

  private

  def submit
    #Nothing needed here
  end

end

app/models/form.rb
class Form
  include ActiveModel::Model

  # Submits the form after strict validation
  # @raise [StandardError] If anything goes wrong (no return values)
  # @return [void]
  def submit!
    validate!
    submit
  end

  private

  # @!method submit
  #   @abstract Subclass should implement {#submit} to perform form submission
  #   @return [void]
end

app/models/githubcall.rb
require 'net/http'
require 'json'
require 'uri'

class Githubcall < ActiveRecord::Base

  include ActiveModel::Model

  attr_accessor :response

  # @return [String] Address of the GitHub API page for user events, minus the username and suffix
  class_attribute :source_url, default: 'https://api.github.com/users/'

  class << self
    # @param [String] GitHub username
    # @return [Object]
    def retrieve(username)
      uri = URI.parse(self.source_url + username + "/events")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      get_response = http.request(Net::HTTP::Get.new(uri.request_uri))

      #If the API is inaccessible or the GitHub user does not exist, raise an error.
      raise Error::CallError if not get_response.is_a?(Net::HTTPSuccess)

      response = Hash.new
      response = {
        data: JSON.parse(get_response.body)
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from StandardError do |error|
    log_error(error)
    render "errors/standard_error", status: :internal_server_error
  end

  rescue_from Error::NameInvalidError do |error|
    Rails.logger.error(error)
    render :invalid, status: :forbidden
  end

  rescue_from Error::CallError do |error|
    Rails.logger.error(error)
    render :call_error, status: :forbidden
  end

  private

  # Log an exception
  def log_error(error)
    logger.error({
      error: "#{error.inspect}",
      cause: "#{error.cause.inspect}",
    })
  end

  # Perform a redirect but keep all existing request parameters
  # This is a workaround for not being able to redirect a POST/PUT request.
  def redirect_with_params(opts={})
    redirect_to request.parameters.update(opts)
  end
end

app/controllers/event_forms_controller.rb
class EventFormsController < ApplicationController

  #Load a new instance of the form
  before_action :init_form!

  def index
    redirect_to action: :new
  end

  def create
    @form.submit!
    #Check user input and provide feedback if the user name does not follow GitHub rules.
    @form.validate_name!(params["event_form"]["user_name"])
    #Do some basic string cleaning to protect against malicious input.
    safe_name = @form.sanitize_name!(params["event_form"]["user_name"])
    #If there is not a successful API call, the rescue_from in the base class will render the call_error view.
    #Otherwise, print out the GitHub events for the specified user in the create view.
    render locals: {
      github_event: Githubcall.retrieve(safe_name),
      username: params["event_form"]["user_name"]
    }
  rescue ActiveModel::ValidationError => e
    Rails.logger.error(e)
    flash[:danger] ||= []
    @form.errors.full_messages.each{|msg| flash[:danger] << msg}
    redirect_with_params(action: :new)
  end

  def show
    if %w(invalid call_eror).include?(params[:id])
      render params[:id]
    else
      redirect_to action: :new
    end
  end

  private

  def init_form!
    #Instantiate new form object
    @form = EventForm.new()
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(model)
    return unless model.errors.any?

    content_tag(:div, class: "alert alert-warning") do
      concat content_tag(:h5, 'Please correct these errors:')

      content_tag(:ul) do
        model.errors.full_messages.each do |msg|
          concat content_tag(:li, msg).html_safe
        end
      end
    end
  end
end

app/views/event_forms/call_error.html.erb
<br />
<div class="notice" style="font-family: Arial;">Something went wrong with the API call or the GitHub user does not exist. Please check the user name and try back another time.</div>

app/views/event_forms/create.html.erb
<style type="text/css">
  h1 {
    font-family: Arial;
    font-size: 1.5em;
    text-align: center;
  }
  td {
    font-family: Arial;
    font-size: 1em;
  }
</style>

<h1>GitHub Events for <%= username %></h1>

<br />

<table>
<% for @event in github_event[:data] %>
	<tr>
	<td style="padding:10px">Event ID: <%= @event['id'] %></td>
	<td style="padding:10px">Event Type: <%= @event['type'] %></td>
	<td style="padding:10px">Repo Name: <%= @event['repo']['name'] %></td>
	<td style="padding:10px">Public?: <%= @event['public'] %></td>
	<td style="padding:10px">Date: <%= @event['created_at'] %></td>

</tr>
<% end %>
</table>

app/views/event_forms/invalid.html.erb
<style type="text/css">
  div, li {
    font-family: Arial;
  }
</style>

<div class="notice">You must enter a valid GitHub username into the search box. The specifications are as follows:</div>

<ul>
<li>The username may only contain alphanumeric characters or hyphens.</li>
<li>The username cannot have multiple consecutive hyphens.</li>
<li>The username cannot begin or end with a hyphen.</li>
<li>The username maximum is 39 characters.</li>
</ul>

<div class="return">Click <%= link_to 'here', new_event_form_path %> to try again.</div>

app/views/event_forms/new.html.erb
<%= form_for(@form, class: 'needs-validation') do |f| %>
  <h1 style="font-family: Sans-Serif;">GitHub Events API User Search</h1>

  <br />

  <p style="font-family: Sans-Serif;">Enter in a valid GitHub username to see events info</p>

  <br />

  <%= f.text_field :user_name, required: true, :style => 'width:30%;', :class => "user-name" %><br />

  <br />

  <div class="submit-button">
    <%= f.submit(class: "submit-button") %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gheventsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>